name: mirc
description: mirc Podcast Player

version: 1.3.15+199

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: 3.32.6

dependencies:
  accessibility_tools: ^2.4.1
  app_links: ^6.3.0
  auto_size_text: ^3.0.0
  audio_service: ^0.18.18
  audio_session: ^0.2.1
  collection: ^1.18.0
  connectivity_plus: ^6.0.11
  cupertino_icons: ^1.0.6
  device_info_plus: ^11.5.0
  extended_image: ^10.0.1
  file_picker: ^10.0.0
  flutter_dialogs: ^3.0.0
  flutter_downloader: ^1.12.0
  flutter_html: ^3.0.0
  flutter_html_svg: ^3.0.0
  flutter_html_table: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_spinkit: ^5.0.0
  html: ^0.15.6
  intl: ^0.20.2
  intl_translation: ^0.20.0
  just_audio: ^0.10.4
  logging: ^1.3.0
  meta: ^1.12.0
  mp3_info: ^0.2.0
  path: ^1.8.3
  path_provider: ^2.1.4
  path_provider_platform_interface: ^2.0.4
  percent_indicator: 4.2.5
  permission_handler: ^12.0.0+1
  podcast_search: ^0.7.11
  provider: ^6.0.3
  rxdart: ^0.28.0
  scrollable_positioned_list: ^0.3.7
  sembast: ^3.8.3
  share_plus: ^11.0.0
  shared_preferences: ^2.3.4
  sliver_tools: ^0.2.12
  url_launcher: ^6.3.1
  xml: 6.5.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # flutter_launcher_icons: ^0.14.4

dev_dependencies:
  mockito: ^5.2.0
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  change_app_package_name: ^1.5.0
  flutter_test:
    sdk: flutter




flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/mirc-logo.png"
  adaptive_icon_background: "#003A30"
  adaptive_icon_foreground: "assets/images/mirc-logo.png"
  remove_alpha_ios: true
  fullscreen: true
  web:
    generate: true
    image_path: "assets/images/mirc-logo.png"
    background_color: "#003A30"

flutter_native_splash:
  color: "#0a0a0a"         # background color you want (e.g. dark blue)
  image: assets/images/mirc-logo.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center  # ensures logo stays centered
  ios_content_mode: center


flutter:
  uses-material-design: true

  assets:
    - assets/images/mirc-logo.png

    # Certificate authorities
    - assets/ca/lets-encrypt-r3.pem
    - assets/ca/globalsign-gcc-r6-alphassl-ca-2023.pem

  fonts:
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf

